version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - formats: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  header: |
    ## Exasol Terraform Provider {{ .Version }}

    For detailed release notes, see [RELEASE_NOTES_v{{ .Version }}.md](https://github.com/exasol/bi-terraform-provider-exasol/blob/main/RELEASE_NOTES_v{{ .Version }}.md)

changelog:
  use: github
  sort: asc
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
