version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # explicitly list only the combos we want:
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - formats: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
