name: CI

on:
  push:
    branches: [ main, develop ]
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.25'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run fmt
        run: make fmt

      - name: Run vet
        run: make vet

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: success()

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
  release:
    name: Build & Publish provider binary
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')   # only when a version tag is pushed
    permissions:
      contents: write          # needed to create GitHub Releases
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0       # goreleaser needs tags and full history

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}