name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.25'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run fmt
        run: make fmt

      - name: Run vet
        run: make vet

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate docs
        run: |
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
          make docs
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Documentation is out of date. Please run 'make docs' and commit the changes."
            exit 1
          fi
  
  release:
    name: Build & Publish provider binary
    needs: [test, lint]        # only after tests/lint succeed
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # only when merging/pushing to main
    permissions:
      contents: write          # needed to create GitHub Releases
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0       # goreleaser needs tags and full history
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      # Install goreleaser
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}